import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function generateChartPDF(chartElementId: string, chartData: any): Promise<Blob> {
  const element = document.getElementById(chartElementId);
  if (!element) throw new Error("Chart element not found");

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF("p", "mm", "a4");
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();

  const imgWidth = canvas.width;
  const imgHeight = canvas.height;
  const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
  const width = imgWidth * ratio;
  const height = imgHeight * ratio;

  pdf.setFontSize(20);
  pdf.text("Methjothisa - Birth Chart", pdfWidth / 2, 20, { align: "center" });

  pdf.setFontSize(12);
  pdf.text(`Name: ${chartData.fullName}`, 20, 35);
  pdf.text(`Date of Birth: ${chartData.dateOfBirth}`, 20, 42);
  pdf.text(`Birth Time: ${chartData.birthTime}`, 20, 49);
  pdf.text(`Birth Place: ${chartData.birthPlace}`, 20, 56);

  pdf.addImage(imgData, "PNG", (pdfWidth - width) / 2, 65, width, height);

  pdf.setFontSize(10);
  pdf.text("Generated by Methjothisa - Universal Astro Intelligence Platform", pdfWidth / 2, pdfHeight - 10, { align: "center" });

  return pdf.output("blob");
}

export async function generateReportPDF(title: string, content: string, chartData: any): Promise<Blob> {
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  let yPosition = 20;

  pdf.setFontSize(24);
  pdf.text(title, pageWidth / 2, yPosition, { align: "center" });
  yPosition += 15;

  pdf.setFontSize(12);
  pdf.text(`Name: ${chartData.fullName}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Date of Birth: ${chartData.dateOfBirth}`, 20, yPosition);
  yPosition += 7;
  pdf.text(`Birth Time: ${chartData.birthTime}`, 20, yPosition);
  yPosition += 15;

  const lines = content.split("\n");
  lines.forEach((line) => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setFontSize(11);
    pdf.text(line, 20, yPosition);
    yPosition += 6;
  });

  pdf.setFontSize(10);
  pdf.text("Generated by Methjothisa", pageWidth / 2, 285, { align: "center" });

  return pdf.output("blob");
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
